apiVersion: apps/v1
kind: Deployment
metadata:
  name: &service-name simplegolangk8sdocker
  labels: &labels
    app: *service-name
spec:
  minReadySeconds: 1
  selector:
    matchLabels: *labels
  replicas: 3
  revisionHistoryLimit: 10
  template: 
    metadata:
      labels: *labels
    spec:
      containers:
      - name: *service-name
        image: yersultan/simplegolangk8sdocker:v1
        command: ["./binary"]
        ports:
        - name: back
          containerPort: 8000
        livenessProbe:
          httpGet:
            port: 8000
            path: /health
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 2
        readinessProbe:
          httpGet:
            port: 8000
            path: /health
          initialDelaySeconds: 10
          periodSeconds: 5