apiVersion: v1
kind: Service
metadata:
  name: &service-name simplegolangk8sdocker
spec:
  type: NodePort
  selector:
    app: *service-name
  ports:
    - name: http
      port: 8000
      nodePort: 31123
      protocol: TCP