apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend-app
  template:
    metadata:
      labels:
        app: backend-app
    spec:
      containers:
      - name: backend
        image: yersultan/simplefullstackapp_backend:v1
        command: ["./binary"]
        ports:
        - name: back
          containerPort: 8000
        livenessProbe:
          httpGet:
            port: 8000
            path: /users
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 2
        readinessProbe:
          httpGet:
            port: 8000
            path: /users
          initialDelaySeconds: 10
          periodSeconds: 5